/*
AUTOGENERATED STYLE KERNEL
Settings:
 LMUL = 8 (m8)
 M = 8
 N = 4
 precision = double (FP64)
 unroll = NONE
 Kernel Name: dgemm_kernel_8x4_zvl128b_lmul8_nounroll
*/

#include <riscv_vector.h>

typedef long BLASLONG;
typedef double FLOAT;

int dgemm_kernel_8x4_zvl128b_lmul8_nounroll(
    BLASLONG M, BLASLONG N, BLASLONG K,
    FLOAT alpha, FLOAT *A, FLOAT *B, FLOAT *C, BLASLONG ldc)
{
    BLASLONG gvl = 0;
    BLASLONG m_top = 0;
    BLASLONG n_top = 0;

    /* ================================
       MAIN PASS (N / 4)
       ================================ */

    for (BLASLONG j = 0; j < N / 4; j++) {

        m_top = 0;
        gvl = __riscv_vsetvl_e64m8(8);

        for (BLASLONG i = 0; i < M / 8; i++) {

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

            double B0 = B[bi + 0];
            double B1 = B[bi + 1];
            double B2 = B[bi + 2];
            double B3 = B[bi + 3];
            bi += 4;

            vfloat64m8_t A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
            ai += 8;

            vfloat64m8_t r0 = __riscv_vfmul_vf_f64m8(A0, B0, gvl);
            vfloat64m8_t r1 = __riscv_vfmul_vf_f64m8(A0, B1, gvl);
            vfloat64m8_t r2 = __riscv_vfmul_vf_f64m8(A0, B2, gvl);
            vfloat64m8_t r3 = __riscv_vfmul_vf_f64m8(A0, B3, gvl);

            for (BLASLONG k = 1; k < K; k++) {

                B0 = B[bi + 0];
                B1 = B[bi + 1];
                B2 = B[bi + 2];
                B3 = B[bi + 3];
                bi += 4;

                A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
                ai += 8;

                r0 = __riscv_vfmacc_vf_f64m8(r0, B0, A0, gvl);
                r1 = __riscv_vfmacc_vf_f64m8(r1, B1, A0, gvl);
                r2 = __riscv_vfmacc_vf_f64m8(r2, B2, A0, gvl);
                r3 = __riscv_vfmacc_vf_f64m8(r3, B3, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vfloat64m8_t c0 = __riscv_vle64_v_f64m8(&C[ci], gvl);
            ci += ldc;
            vfloat64m8_t c1 = __riscv_vle64_v_f64m8(&C[ci], gvl);
            ci += ldc;
            vfloat64m8_t c2 = __riscv_vle64_v_f64m8(&C[ci], gvl);
            ci += ldc;
            vfloat64m8_t c3 = __riscv_vle64_v_f64m8(&C[ci], gvl);

            c0 = __riscv_vfmacc_vf_f64m8(c0, alpha, r0, gvl);
            c1 = __riscv_vfmacc_vf_f64m8(c1, alpha, r1, gvl);
            c2 = __riscv_vfmacc_vf_f64m8(c2, alpha, r2, gvl);
            c3 = __riscv_vfmacc_vf_f64m8(c3, alpha, r3, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse64_v_f64m8(&C[ci], c0, gvl);
            ci += ldc;
            __riscv_vse64_v_f64m8(&C[ci], c1, gvl);
            ci += ldc;
            __riscv_vse64_v_f64m8(&C[ci], c2, gvl);
            ci += ldc;
            __riscv_vse64_v_f64m8(&C[ci], c3, gvl);

            m_top += 8;
        }

        n_top += 4;
    }

    /* ================================
       N TAIL = 2
       ================================ */

    if (N & 2) {

        gvl = __riscv_vsetvl_e64m8(8);
        m_top = 0;

        for (BLASLONG i = 0; i < M / 8; i++) {

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

            double B0 = B[bi];
            double B1 = B[bi + 1];
            bi += 2;

            vfloat64m8_t A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
            ai += 8;

            vfloat64m8_t r0 = __riscv_vfmul_vf_f64m8(A0, B0, gvl);
            vfloat64m8_t r1 = __riscv_vfmul_vf_f64m8(A0, B1, gvl);

            for (BLASLONG k = 1; k < K; k++) {

                B0 = B[bi];
                B1 = B[bi + 1];
                bi += 2;

                A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
                ai += 8;

                r0 = __riscv_vfmacc_vf_f64m8(r0, B0, A0, gvl);
                r1 = __riscv_vfmacc_vf_f64m8(r1, B1, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vfloat64m8_t c0 = __riscv_vle64_v_f64m8(&C[ci], gvl);
            ci += ldc;
            vfloat64m8_t c1 = __riscv_vle64_v_f64m8(&C[ci], gvl);

            c0 = __riscv_vfmacc_vf_f64m8(c0, alpha, r0, gvl);
            c1 = __riscv_vfmacc_vf_f64m8(c1, alpha, r1, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse64_v_f64m8(&C[ci], c0, gvl);
            ci += ldc;
            __riscv_vse64_v_f64m8(&C[ci], c1, gvl);

            m_top += 8;
        }

        n_top += 2;
    }

    /* ================================
       N TAIL = 1
       ================================ */

    if (N & 1) {

        gvl = __riscv_vsetvl_e64m8(8);
        m_top = 0;

        for (BLASLONG i = 0; i < M / 8; i++) {

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

            double B0 = B[bi];
            bi += 1;

            vfloat64m8_t A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
            ai += 8;

            vfloat64m8_t r0 = __riscv_vfmul_vf_f64m8(A0, B0, gvl);

            for (BLASLONG k = 1; k < K; k++) {

                B0 = B[bi];
                bi += 1;

                A0 = __riscv_vle64_v_f64m8(&A[ai], gvl);
                ai += 8;

                r0 = __riscv_vfmacc_vf_f64m8(r0, B0, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vfloat64m8_t c0 = __riscv_vle64_v_f64m8(&C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f64m8(c0, alpha, r0, gvl);

            __riscv_vse64_v_f64m8(&C[ci], c0, gvl);

            m_top += 8;
        }

        n_top += 1;
    }

    return 0;
}
