/*
AUTOGENERATED KERNEL
Settings:
 LMUL=1 (m1)
 M=8
 N=4
 precision=int8_t (8-bit integer)
 unroll_factor=2 (Pragma unroll 2)
 Kernel Name: dgemm_kernel_8x4_zvl128b_lmul1_unroll2
*/

#include <riscv_vector.h>
#include <stdint.h>

typedef long BLASLONG;
typedef int8_t FLOAT;

int dgemm_kernel_8x4_zvl128b_lmul1_unroll1(BLASLONG M, BLASLONG N, BLASLONG K, FLOAT alpha, FLOAT *A, FLOAT *B, FLOAT *C, BLASLONG ldc)
{
    BLASLONG gvl = 0;
    BLASLONG m_top = 0;
    BLASLONG n_top = 0;

    // -- MAIN PASS

    for (BLASLONG j = 0; j < N / 4; j += 1) {
        m_top = 0;
        BLASLONG gvl = __riscv_vsetvl_e8m1(8);

        for (BLASLONG i = 0; i < M / 8; i += 1) {
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            int8_t B1 = B[bi + 1];
            int8_t B2 = B[bi + 2];
            int8_t B3 = B[bi + 3];
            bi += 4;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 8;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);
            vint8m1_t result1 = __riscv_vmul_vx_i8m1(A0, B1, gvl);
            vint8m1_t result2 = __riscv_vmul_vx_i8m1(A0, B2, gvl);
            vint8m1_t result3 = __riscv_vmul_vx_i8m1(A0, B3, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                B1 = B[bi + 1];
                B2 = B[bi + 2];
                B3 = B[bi + 3];
                bi += 4;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 8;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
                result1 = __riscv_vmacc_vx_i8m1(result1, B1, A0, gvl);
                result2 = __riscv_vmacc_vx_i8m1(result2, B2, A0, gvl);
                result3 = __riscv_vmacc_vx_i8m1(result3, B3, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c1 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c2 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c3 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);
            c1 = __riscv_vmacc_vx_i8m1(c1, alpha, result1, gvl);
            c2 = __riscv_vmacc_vx_i8m1(c2, alpha, result2, gvl);
            c3 = __riscv_vmacc_vx_i8m1(c3, alpha, result3, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c1, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c2, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c3, gvl);
            m_top += 8;
        }

        // -- tails for main pass

        if (M & 4) {
            gvl = __riscv_vsetvl_e8m1(4);

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            int8_t B1 = B[bi + 1];
            int8_t B2 = B[bi + 2];
            int8_t B3 = B[bi + 3];
            bi += 4;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 4;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);
            vint8m1_t result1 = __riscv_vmul_vx_i8m1(A0, B1, gvl);
            vint8m1_t result2 = __riscv_vmul_vx_i8m1(A0, B2, gvl);
            vint8m1_t result3 = __riscv_vmul_vx_i8m1(A0, B3, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                B1 = B[bi + 1];
                B2 = B[bi + 2];
                B3 = B[bi + 3];
                bi += 4;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 4;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
                result1 = __riscv_vmacc_vx_i8m1(result1, B1, A0, gvl);
                result2 = __riscv_vmacc_vx_i8m1(result2, B2, A0, gvl);
                result3 = __riscv_vmacc_vx_i8m1(result3, B3, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c1 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c2 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c3 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);
            c1 = __riscv_vmacc_vx_i8m1(c1, alpha, result1, gvl);
            c2 = __riscv_vmacc_vx_i8m1(c2, alpha, result2, gvl);
            c3 = __riscv_vmacc_vx_i8m1(c3, alpha, result3, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c1, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c2, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c3, gvl);
            m_top += 4;
        }

        if (M & 2) {
            int8_t result0 = 0;
            int8_t result1 = 0;
            int8_t result2 = 0;
            int8_t result3 = 0;
            int8_t result4 = 0;
            int8_t result5 = 0;
            int8_t result6 = 0;
            int8_t result7 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                result1 += A[ai + 1] * B[bi + 0];
                result2 += A[ai + 0] * B[bi + 1];
                result3 += A[ai + 1] * B[bi + 1];
                result4 += A[ai + 0] * B[bi + 2];
                result5 += A[ai + 1] * B[bi + 2];
                result6 += A[ai + 0] * B[bi + 3];
                result7 += A[ai + 1] * B[bi + 3];
                ai += 2;
                bi += 4;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            C[ci + 0 * ldc + 1] += alpha * result1;
            C[ci + 1 * ldc + 0] += alpha * result2;
            C[ci + 1 * ldc + 1] += alpha * result3;
            C[ci + 2 * ldc + 0] += alpha * result4;
            C[ci + 2 * ldc + 1] += alpha * result5;
            C[ci + 3 * ldc + 0] += alpha * result6;
            C[ci + 3 * ldc + 1] += alpha * result7;
            m_top += 2;
        }

        if (M & 1) {
            int8_t result0 = 0;
            int8_t result1 = 0;
            int8_t result2 = 0;
            int8_t result3 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                result1 += A[ai + 0] * B[bi + 1];
                result2 += A[ai + 0] * B[bi + 2];
                result3 += A[ai + 0] * B[bi + 3];
                ai += 1;
                bi += 4;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            C[ci + 1 * ldc + 0] += alpha * result1;
            C[ci + 2 * ldc + 0] += alpha * result2;
            C[ci + 3 * ldc + 0] += alpha * result3;
            m_top += 1;
        }

        n_top += 4;
    }

    // -- tails for N=2

    if (N & 2) {
        gvl = __riscv_vsetvl_e8m1(8);
        m_top = 0;

        for (BLASLONG i = 0; i < M / 8; i += 1) {
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            int8_t B1 = B[bi + 1];
            bi += 2;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 8;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);
            vint8m1_t result1 = __riscv_vmul_vx_i8m1(A0, B1, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                B1 = B[bi + 1];
                bi += 2;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 8;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
                result1 = __riscv_vmacc_vx_i8m1(result1, B1, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c1 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);
            c1 = __riscv_vmacc_vx_i8m1(c1, alpha, result1, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c1, gvl);
            m_top += 8;
        }

        if (M & 4) {
            gvl = __riscv_vsetvl_e8m1(4);

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            int8_t B1 = B[bi + 1];
            bi += 2;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 4;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);
            vint8m1_t result1 = __riscv_vmul_vx_i8m1(A0, B1, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                B1 = B[bi + 1];
                bi += 2;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 4;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
                result1 = __riscv_vmacc_vx_i8m1(result1, B1, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            ci += ldc - gvl * 0;
            vint8m1_t c1 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);
            c1 = __riscv_vmacc_vx_i8m1(c1, alpha, result1, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            ci += ldc - gvl * 0;
            __riscv_vse8_v_i8m1(&C[ci], c1, gvl);
            m_top += 4;
        }

        if (M & 2) {
            int8_t result0 = 0;
            int8_t result1 = 0;
            int8_t result2 = 0;
            int8_t result3 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                result1 += A[ai + 1] * B[bi + 0];
                result2 += A[ai + 0] * B[bi + 1];
                result3 += A[ai + 1] * B[bi + 1];
                ai += 2;
                bi += 2;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            C[ci + 0 * ldc + 1] += alpha * result1;
            C[ci + 1 * ldc + 0] += alpha * result2;
            C[ci + 1 * ldc + 1] += alpha * result3;
            m_top += 2;
        }

        if (M & 1) {
            int8_t result0 = 0;
            int8_t result1 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                result1 += A[ai + 0] * B[bi + 1];
                ai += 1;
                bi += 1;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            C[ci + 1 * ldc + 0] += alpha * result1;
            m_top += 1;
        }

        n_top += 2;
    }

    // -- tails for N=1

    if (N & 1) {
        gvl = __riscv_vsetvl_e8m1(8);
        m_top = 0;

        for (BLASLONG i = 0; i < M / 8; i += 1) {
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            bi += 1;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 8;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                bi += 1;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 8;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            m_top += 8;
        }

        if (M & 4) {
            gvl = __riscv_vsetvl_e8m1(4);

            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;
            int8_t B0 = B[bi + 0];
            bi += 1;

            vint8m1_t A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
            ai += 4;

            vint8m1_t result0 = __riscv_vmul_vx_i8m1(A0, B0, gvl);

#pragma GCC unroll 2
            for (BLASLONG k = 1; k < K; k++) {
                B0 = B[bi + 0];
                bi += 1;

                A0 = __riscv_vle8_v_i8m1(&A[ai + 0 * gvl], gvl);
                ai += 4;

                result0 = __riscv_vmacc_vx_i8m1(result0, B0, A0, gvl);
            }

            BLASLONG ci = n_top * ldc + m_top;

            vint8m1_t c0 = __riscv_vle8_v_i8m1(&C[ci], gvl);
            c0 = __riscv_vmacc_vx_i8m1(c0, alpha, result0, gvl);

            ci = n_top * ldc + m_top;

            __riscv_vse8_v_i8m1(&C[ci], c0, gvl);
            m_top += 4;
        }

        if (M & 2) {
            int8_t result0 = 0;
            int8_t result1 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                result1 += A[ai + 1] * B[bi + 0];
                ai += 2;
                bi += 1;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            C[ci + 0 * ldc + 1] += alpha * result1;
            m_top += 2;
        }

        if (M & 1) {
            int8_t result0 = 0;
            BLASLONG ai = m_top * K;
            BLASLONG bi = n_top * K;

#pragma GCC unroll 2
            for (BLASLONG k = 0; k < K; k++) {
                result0 += A[ai + 0] * B[bi + 0];
                ai += 1;
                bi += 1;
            }

            BLASLONG ci = n_top * ldc + m_top;
            C[ci + 0 * ldc + 0] += alpha * result0;
            m_top += 1;
        }

        n_top += 1;
    }

    return 0;
}
