CC = gcc

CFLAGS = -O3 \
         -march=rv64gcv_zvl256b \
         -mabi=lp64d \
         -std=c11 \
         -Wall

TARGET = bench

KERNEL = sgemm_kernel_16x8_zvl256b_lmul1_opt_unroll2.c
BENCH  = sgemm_bench.c

all: $(TARGET)

$(TARGET): $(KERNEL) $(BENCH)
	$(CC) $(CFLAGS) $(KERNEL) $(BENCH) -o $(TARGET)

clean:
	rm -f $(TARGET)
